export const actionTypes = {
    ADD_TIP: 'ADD_TIP',
    SET_IS_SAVED: 'SET_IS_SAVED',
    REMOVE_TIP: 'REMOVE_TIP',
    NUMBER_INPUT_CHANGED: 'NUMBER_INPUT_CHANGED',
    NAME_INPUT_CHANGED: 'NAME_INPUT_CHANGED',
    SET_NUMBERS: 'SET_NUMBERS',
};
